cuda: False
ngpu: 1
gpu_id: '0'
data_dir: ./Train     # Your dataset path
video_flist: './filelists/Video_Name_List.txt'
audio_flist: './filelists/Audio_Name_List.txt'
workers: 4
batchSize: 40
checkpoint_folder: ./checkpoints
init_model_lrt: './def_model/lrt_model_test.h5'
para_model_lrt: './def_model/lrt_model_para.npy'
topk: 5
